signalfx/splunk-otel-js-web

INSTALLING.md
README.md

Add a new INSTALLING.md document and link it from README.

Document other installation options

---

integration-tests/tests/docload/docload.spec.js

Mostly event timestamps, ordering and reliability of such.  Expecting to fight with browsers to make this work.

Improved testing of docload

---

README.md
integration-tests/tests/spanprocessor/spanprocessor.ejs
integration-tests/tests/spanprocessor/spanprocessor.spec.js
integration-tests/utils/globals.js
package.json
src/main.js

Integration test showing how it works, documentation changes, and package.json fixes to
make debugging something like this easier (npm start works again).

Add spanProcessor as option for filtering spans.

---

integration-tests/devServer/devServer.js
integration-tests/tests/docload/docload.spec.js

link.* fields for documentFetch and resourceFetch, resource fetch for 404 image.

Yet more docload testing

---

rollup.helpers.js
src/xhrfetch.js
test/patchchecks.test.js

chore: sync with upstream

---

integration-tests/tests/docload/docload.spec.js

Upstream otel fixed the docload trace issue

---

integration-tests/tests/cookies/cookies.spec.js
integration-tests/tests/docload/docload.spec.js
integration-tests/tests/fetch/fetch.spec.js
integration-tests/tests/init/init.spec.js
integration-tests/tests/longtask/index.spec.js
integration-tests/tests/server-timing/index.spec.js
integration-tests/tests/user-interaction/causality.spec.js
integration-tests/tests/user-interaction/forms.spec.js
integration-tests/tests/user-interaction/history.spec.js
integration-tests/tests/user-interaction/keyboard.spec.js
integration-tests/tests/user-interaction/mouse.spec.js
integration-tests/tests/websocket/websockets.spec.js
integration-tests/tests/webvitals/webvitals.spec.js
integration-tests/tests/xhr/xhr-basic.spec.js
integration-tests/utils/globals.js
src/longtask.js

fix: trying to supportedEntryTypes which may not exist

---

README.md
docs/CONTRIBUTING.md
package.json
scripts/release-cdn.mjs

- --dry-run mode
- updated release instructions
- integrity for script snippets

improv: safer releasing to CDN

---

README.md
integration-tests/tests/init/attributes.ejs
integration-tests/tests/init/init.spec.js
src/index.js
test/init.test.js

Instead of overwriting globalAttributes merge

---

README.md
docs/ServerTraceContext.md

- Access-Control-Expose-Headers for Server-Timing
- errors as a potential source of PII

Additional documentation tweaks

---

CHANGELOG.md
package-lock.json
package.json

* Include TS types and esm in release

Release v0.5.1

---

integration-tests/tests/fetch/fetch-post.ejs
integration-tests/tests/fetch/fetch.spec.js
integration-tests/tests/user-interaction/mouse-bubble.ejs
integration-tests/tests/user-interaction/mouse.spec.js
src/SplunkFetchInstrumentation.ts
src/SplunkUserInteractionInstrumentation.ts
utils/devServer/devServer.js

Monkey-patch fixes to our current important issues (fetch with Request object, this inside event listeners) until they are properly released.
To be merged & released on monday, if contrib gets 0.25 released first, then update otel first (WIP #239) and remove published fixes from this pr.

Monkey-patch unreleased fixes

---

integration-tests/tests/cdn/index.spec.js
integration-tests/tests/errors/index.spec.js
integration-tests/tests/webvitals/webvitals.ejs
integration-tests/tests/webvitals/webvitals.spec.js
package-lock.json
package.json

Update web-vitals library to 2.0.0. Has some changes how CLS is calculated

Update web-vitals and update tests

---

docs/Installation.md

After conversation with @t2t2.

Clarify RUM-APM linkage

---

integration-tests/tests/cdn/index.spec.js
integration-tests/tests/longtask/index.spec.js

postrelease: 0.10.3

---

.gitlab-ci.yml

Enable internal Fossa scanning - results are in gitlab.

chore: fossa

---

src/SplunkDocumentLoadInstrumentation.ts
src/SplunkPostDocLoadResourceInstrumentation.ts

Reduce the amount of "Tag value not defined" in UI

Add http method to {document,resource}Fetch spans

---

integration-tests/tests/cdn/index.spec.js

Update cdn test to reflect the rollback version

postrelease: 0.12.5

---

src/SplunkUserInteractionInstrumentation.ts

Got a weird case where for on a specific client website some reason in IE `[object FunctionWrapper]` is used as listener. I assume that wrapper somehow gets translated into a working listener (maybe there's some extension shenanigans), but otel has no idea what to do with that object (as it expects object -> has handleEvent method). So "fixing" by skipping otel's provided wrapper

Skip patching user interactions where it's not possible by instrumentation

---

package-lock.json
packages/web/integration-tests/tests/cdn/index.spec.js
packages/web/package.json
packages/web/src/index.ts

Error gets caught by console.error capturing instrumentation -> people complain about it showing up as an error instead of... y'know, not doing it
_sigh_

Downgrade error when init is called multiple times to warning

---

docs/Configuration.md
packages/web/integration-tests/tests/context/fetch-then.ejs
packages/web/integration-tests/tests/context/location-hash.ejs
packages/web/integration-tests/tests/context/messageport-addeventlistener.ejs
packages/web/integration-tests/tests/context/messageport-cors-inner.ejs
packages/web/integration-tests/tests/context/messageport-cors.ejs
packages/web/integration-tests/tests/context/messageport-onmessage.ejs
packages/web/integration-tests/tests/context/mutation-observer-textnode.ejs
packages/web/integration-tests/tests/context/promise.ejs
packages/web/integration-tests/tests/context/set-immediate.ejs
packages/web/integration-tests/tests/context/set-timeout.ejs
packages/web/integration-tests/tests/context/xhr-events-removed.ejs
packages/web/integration-tests/tests/context/xhr-events.ejs
packages/web/integration-tests/tests/context/xhr-onload.ejs
packages/web/src/SplunkContextManager.ts

Basically a configuration default value change

Enable async context manager by default

---

docs/Instrumentations.md
package-lock.json
packages/web/integration-tests/tests/webvitals/webvitals.spec.js
packages/web/package.json
packages/web/src/SplunkDocumentLoadInstrumentation.ts
packages/web/src/webvitals.ts

Update web-vitals and add INP as reported web-vital

Add web-vitals INP

---

docs/Configuration.md
package-lock.json
packages/web/integration-tests/tests/context/fetch-then.ejs
packages/web/integration-tests/tests/context/location-hash.ejs
packages/web/integration-tests/tests/context/messageport-addeventlistener.ejs
packages/web/integration-tests/tests/context/messageport-cors-inner.ejs
packages/web/integration-tests/tests/context/messageport-cors.ejs
packages/web/integration-tests/tests/context/messageport-onmessage.ejs
packages/web/integration-tests/tests/context/mutation-observer-textnode.ejs
packages/web/integration-tests/tests/context/promise.ejs
packages/web/integration-tests/tests/context/set-immediate.ejs
packages/web/integration-tests/tests/context/set-timeout.ejs
packages/web/integration-tests/tests/context/xhr-events-removed.ejs
packages/web/integration-tests/tests/context/xhr-events.ejs
packages/web/integration-tests/tests/context/xhr-onload.ejs
packages/web/integration-tests/tests/user-interaction/causality.ejs
packages/web/package.json
packages/web/src/SplunkContextManager.ts

This reverts commit b564db40fc09b7bf0913035b22146ecdec397e0f.
Revert async context manager as potential reason behind interaction issues

Revert "Enable async context manager by default (#539)"

---

docs/Configuration.md
packages/web/integration-tests/tests/cdn/index.spec.js
packages/web/src/index.ts
packages/web/test/init.test.ts

Aligning with signalfx/gdi-specification

config: add realm option

---

README.md
packages/session-recorder/README.md
packages/web/README.md

* Fixed gh actions badge
* Added npm badge with link

Fix & update badges

---

CONTRIBUTING.md

Update contributing.md to match template

---

.github/workflows/check-links.yml
.lycheeignore
docs/API.md
docs/DataModel.md
docs/Workflows.md
packages/web/README.md

Add Lychee Link Checker GitHub Action

---

packages/session-recorder/src/index.ts

Consistency with rum library and user convenience

session recorder: add realm config option

---

README.md
packages/web/README.md

Update readme to point to o11y docs/add troubleshooting section

---

packages/session-recorder/package.json
packages/web/package.json

#719 added instrumentation code in folders but missed out on folders not being included in the npm pack
<details><summary>npm pack output w/ change</summary>
```
% npm pack -w packages/web 
npm notice 
npm notice 📦  @splunk/otel-web@0.17.0-beta.0
npm notice === Tarball Contents === 
npm notice 11.4kB LICENSE                                                       
npm notice 2.8kB  README.md                                                     
npm notice 1.3kB  dist/cjs/EventTarget.d.ts                                     
npm notice 1.7kB  dist/cjs/EventTarget.js                                       
npm notice 1.0kB  dist/cjs/EventTarget.js.map …
```

Fix folders being ignored while packing

---

.gitignore
.npmrc
package-lock.json
packages/web/karma.conf.js
packages/web/package.json

* Add npm config that disables tag on version (this needs to be done after release pr manually)
* Update chromedriver

Repo maintance: Add missing config, update chromedriver

---

.github/actions/setup/action.yml
.github/workflows/check-links.yml
.github/workflows/ci-main.yml
.github/workflows/ci.yml

Created a common setup action to eliminate repetition.
_List Github issue(s) which this PR fixes._
N/A

chore: create setup action

---

.github/workflows/ci-main.yml
.github/workflows/ci.yml
.size-limit.cjs
eslint.config.mjs
package-lock.json
package.json

Ensure that nothing is published incidentally that would increase the size of the artifacts. The size check is enforced in CI.
N/A

chore: check size of artifacts

---

package-lock.json
packages/web/package.json

chore: bump chromedriver

---

.github/actions/install-playwright/action.yml
.github/workflows/tests.yml
package-lock.json
packages/integration-tests/package.json
packages/integration-tests/src/tests/docload/docload.spec.ts
packages/web/src/SplunkDocumentLoadInstrumentation.ts

Adds response.status to all resourceFetch spans.

feat: add responseStatus to all resources

---

.github/actions/install-playwright/action.yml
.github/actions/setup/action.yml
.github/workflows/tests.yml
.gitlab-ci.yml
package-lock.json
package.json
packages/session-recorder/package.json
packages/web/package.json

chore: update to node:22

---

packages/integration-tests/src/tests/bots/bots-disabled.ejs
packages/integration-tests/src/tests/bots/bots-enabled.ejs
packages/web/src/index.ts
packages/web/src/types/config.ts
packages/web/test/SplunkContextManager.test.ts
packages/web/test/SplunkOtelWeb.test.ts
packages/web/test/api.test.ts
packages/web/test/init.test.ts
packages/web/test/nodejs.test.ts
packages/web/test/utils.ts

Enable bots by default, add flag to disable them.

feat: enable bots by default

---

packages/web/src/utils/throttle.ts

Small improvements to `throttle` function

chore: improve throttle function

---

packages/web/src/session/cookie-session.ts

It is already decoded in `findCookieValue` function

chore: remove double decode

---

packages/web/src/utils/throttle.ts

- Remove visibility listener when timeout occurs
- Clear timeout when visibility listener triggers

fix: throttle function

---

packages/build-plugins/src/httpUtils.ts
packages/build-plugins/src/utils.ts
packages/build-plugins/src/webpack/index.ts
packages/build-plugins/test/utils.test.ts

Upload endpoint is now available, update the code to use it

feat(build-plugins): use proper URL and auth for source map upload

---

.github/dependabot.yml

chore(dependabot): increase PR limit

---

package-lock.json
package.json

_Replace this with a description of the PR. Explain the problem it solves and the proposed solution._
_List Github issue(s) which this PR fixes._
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

chore: remove unused @octokit/graphql

---

examples/installing-npm/package-lock.json
examples/installing-npm/package.json
examples/next-ssr-example/package-lock.json
examples/next-ssr-example/package.json
examples/todolist/package-lock.json
examples/todolist/package.json
packages/integration-tests/src/tests/cdn/index.spec.ts

Postversion changes
- Chore or internal change (changes not visible to the consumers of the package

chore: postversion 0.20.1

---

.size-limit.cjs
package-lock.json
packages/integration-tests/src/tests/docload/docload.ejs
packages/integration-tests/src/tests/docload/docload.spec.ts
packages/integration-tests/src/tests/resource-observer/resources.ejs
packages/web/src/SplunkDocumentLoadInstrumentation.ts
packages/web/src/SplunkPostDocLoadResourceInstrumentation.ts

Fix issue with duplicated spans when load event is triggered manually

fix: do not duplicate spans when load event is triggered manually from code

---

examples/installing-npm/package-lock.json
examples/installing-npm/package.json
examples/next-ssr-example/package-lock.json
examples/next-ssr-example/package.json
examples/todolist/package-lock.json
examples/todolist/package.json
packages/integration-tests/src/tests/cdn/index.spec.ts

chore: postversion v0.20.2

---

examples/installing-npm/package-lock.json
examples/installing-npm/package.json
examples/next-ssr-example/package-lock.json
examples/next-ssr-example/package.json
examples/todolist/package-lock.json
examples/todolist/package.json
packages/integration-tests/src/tests/cdn/index.spec.ts

chore(postrelease): v0.20.3

---

packages/web/src/storage/local-store.ts

chore: remove console log

---

.gitlab-ci.yml
packages/build-plugins/integration-test/project/package-lock.json

Add dist artifact for build plugins - without it we are not able to run unit tests in gitlab.

chore: missing artifacts for build plugins tests

---

.gitlab-ci.yml

Gitlab - build project before unit tests

chore(internal): build project before unit tests

---

packages/session-recorder/src/recorder/splunk-recorder.ts

If session recording starts while the tab is hidden, we should wait until the tab becomes visible (in the foreground) before beginning the recording.

chore: do not start recording in hidden tab

---

packages/session-recorder/src/session-replay/cdn-module.d.ts
packages/session-recorder/src/session-replay/cdn-module.ts
packages/session-recorder/webpack.lock

Update session replay package to include new `lastKnowSegmentEndUnixMs`

feat: update session replay package

---

packages/session-recorder/src/session-replay/cdn-module.d.ts
packages/session-recorder/src/session-replay/cdn-module.ts
packages/session-recorder/webpack.lock

chore: update session replay package

---

packages/session-recorder/src/export-log-queue.ts

Fixes segment persistence - metadata was missing

fix: segment persistence

---

.lycheeignore
packages/session-recorder/README.md
packages/session-recorder/src/session-replay/cdn-module.d.ts
packages/session-recorder/src/session-replay/cdn-module.ts
packages/session-recorder/src/session-replay/recorder.ts
packages/session-recorder/webpack.config.js
packages/session-recorder/webpack.lock
scripts/release-cdn.mts

Include background service worker for session replay in build

chore(session-replay): include background service

---

packages/session-recorder/src/index.ts
packages/web/src/index.ts

- Add comprehensive error handling to all public API methods in `SplunkRum` and `SplunkSessionRecorder`
- Wrap `init()` methods in try-catch blocks to prevent uncaught exceptions
- Unify error/warning message format with consistent `[Splunk]:` prefix and actionable guidance
- Ensure graceful degradation when internal exceptions occur during initialization or operation
- Improve developer experience with clear, structured error messages and troubleshooting hints

fix: wrap public API methods with try-catch for graceful error handling
