integration-tests/tests/fetch/fetch-ignored.ejs
src/main.js

1. Fetch url ignoring broken at the moment.  Fetch Instrumentation constructor takes config not provider and config.
2. Test for it was also broken because fetch spans are ended 300ms after fetch end in order to make sure timings are present when ending span.  So guard-span arrived before fetch spans and test passed although it was broken.

Fix fetch url ignoring. 

---

integration-tests/tests/docload/docload-all.ejs
integration-tests/tests/docload/docload.spec.js
integration-tests/tests/docload/iframe.ejs
package.json
src/docload.js

Ignore fetch,xhr, beacon happening before load event.
Fetch,xhr will be reported by their instrumentation and beacon is just noise.

Ignore some asset types during docload

---

src/xhrfetch.js

Chrome will show and error in console otherwise.
More info: https://trackjs.com/blog/refused-unsafe-header/
Lower casing headers is done because in Safari 10 getAllResponseHeaders is upper case but in all other tested 
browsers it is not.

Do a safety check before asking for xhr header.

---

rollup.shared.js

Noticed while manually testing in IE that there was an odd syntax error from for ... of statements instead of the error from `throwIfUnsupportedBrowser.js` as expected. Then noticed that only our files (everything in `src/` folders) weren't being touched by babel and were in their raw form in built files (class syntax and all). Removing the filter so absolutely all files get babel treatment

Fix babel not transpiling our files

---

examples/installing-npm/README.md

Update @splunk/splunk-otel-web to @splunk/otel-web npm examples.

Fix package name in npm examples

---

integration-tests/tests/cookies/cookies.spec.js
integration-tests/tests/errors/index.spec.js

This causes nightwatch to get stuck if there's a failure in a spec at the end
of which we wait for the browser to end.

fix: don't wait for browser to end

---

test/websockets.test.ts

Original issue (APMI-1375) was that `reconnecting-websocket` couldn't use instrumented WebSocket because [`WebSocket.CLOSING` value was missing](https://github.com/pladaria/reconnecting-websocket/blob/05a2f7cb0e31f15dff5ff35ad53d07b1bec5e197/reconnecting-websocket.ts#L20). Typescript conversion [changed instrumenting from function to class extends](https://github.com/signalfx/splunk-otel-js-web/pull/143/files#diff-845430eee1ed1832871e1940f0cdf91ff03823313ba893e20e99ab82cb665237R49) and that pretty much fixed the issue. Adding an extra test to make sure it will stay that way.

WebSocket instrumentation: Add extra test to check for static props

---

docs/ManualInstrumentation.md
docs/MigratingInstrumentation.md

Recommend using `@opentelemetry/api` for manually instrumenting for better interoperability and avoiding confusion about having to pass SplunkRUM around when dealing with multiple applications on the same page

Update documentation for manual instrumentation

---

scripts/release-cdn.mjs

As pointed out by tests invalidation isn't quite working and some are returning 0.5.0 instead of 0.5.1

Fix CDN invalidation path

---

.eslintrc.js
integration-tests/tests/visibility/visibility.ejs
integration-tests/tests/visibility/visibility.spec.js
integration-tests/utils/globals.js
package-lock.json
package.json
src/SplunkLongTaskInstrumentation.ts
src/SplunkPageVisibilityInstrumentation.ts
src/index.ts
test/utils.ts

Captured as 0 duration spans as these can't be complete spans(due to us not being able to close some of them in some case) and we don't have events. Disabled for now cause we need to make sure that sending them is fine. At some point we probably need to add this info to each span so data can be filtered in UI.
Code in index.ts is moved cause otherwise some things fire at wrong times.

Capture visibility events

---

CHANGELOG.md
docs/Async-Traces.md
integration-tests/tests/context/async-context.spec.js
integration-tests/tests/context/location-hash.ejs
src/SplunkContextManager.ts
src/index.ts

Improve async context context manager support for hash based routers and add a note to documentation about code split usage.
[Angularjs' router](https://github.com/angular/angular.js/blob/9bff2ce8fb170d7a33d3ad551922d7e23e9f82fc/src/ng/browser.js#L242) changes the hash and then waits for browser to fire hashchange event to do rest of the transition (load components, fire them, etc...). Added linking context in that case by watching if location.hash value changed within the function called with contextmanager.with
We can't link code executed in <script> tag that was loaded by user interaction, so added a note to documentation on how it can be supported.

Async context: Improve hash based router support, note on code splitting

---

CHANGELOG.md
src/servertiming.ts
test/servertiming.test.ts

Have a support case where server-timings header value is inserted with single quotes - PerformanceEntries can process both types of quotes while regexp couldn't, causing only docload to be linked

Support single quote in server-timings header

---

integration-tests/tests/errors/index.spec.js
integration-tests/tests/errors/views/unhandled-rejection.undefined.ejs
src/SplunkErrorInstrumentation.ts

```js
Promise.reject()
```
Causes error instrumentation to break on `arg.toString()`

Handle undefined errors more gracefully

---

integration-tests/tests/native/native.ejs
integration-tests/tests/native/native.spec.js
src/session.ts

SplunkRum mobile components support embedding SplunkRumNative into WebView instances.  When present,
prefer the native app's session ID to our cookie.,

Use SplunkRumNative.getNativeSessionId when present

---

README.md
docs/Configuration.md
docs/Sampling.md
src/SessionBasedSampler.ts
src/index.ts
src/throwIfUnsupportedBrowser.ts
test/SessionBasedSampler.test.ts
test/index.ts

- Allows configuring tracer
- Adds custom sampler that uses session id to determine if traces should be sampled

Session based sampler, expose tracer configuration

---

integration-tests/tests/user-interaction/causality.spec.js
src/SplunkUserInteractionInstrumentation.ts
test/init.test.ts

Issues with angular: https://codesandbox.io/s/angular-material-tooltip-fhimx?file=/src/index.html
1. Tooltip location isn't properly updated as while it waits for [ngzone's microtask queue to flush out](https://github.com/angular/components/blob/7dbe9a42829a2e71cca3363e9a97ec0ea45be276/src/material/tooltip/tooltip.ts#L560), the microtask never existed due to us patching Node (as a fix for IE not having EventTarget) vs zone patching EventTarget or Node depending on browser support. Node is before EventTarget in prototype chain so even though zone patches addEventListener later, it will never get called as Node's addEventListener is found first.
Upstreamed version of the IE fix matches zone's patching = doesn't cause this issue, so fixing by removing our version of the fix. 
2. After …

Cleanup upstreamed patches & fix angular

---

docs/Configuration.md
docs/Instrumentations.md
integration-tests/tests/socketio/socketio.before.ejs
integration-tests/tests/socketio/socketio.ejs
integration-tests/tests/socketio/socketio.spec.js
karma.conf.js
package-lock.json
package.json
src/SplunkSocketIoClientInstrumentation.ts
src/index.ts
src/utils.ts
test/index.ts
test/plugins/socketio-server.js
test/socketio.test.ts
test/synthetics.test.ts
utils/devServer/devServer.js

Adds instrumentation to socket.io client that unlike websocket instrumentation follows the [messaging systems](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md) otel spec, as socket.io usage has the structure needed to make it work. It is also made with [aspecto's socket.io server side instrumentation](https://github.com/aspecto-io/opentelemetry-ext-js/tree/master/packages/instrumentation-socket.io) in mind (spans should be similar, tho with a few omissions that don't apply client side).
Since this is the first instrumentation that instruments a separately loaded library (won't always be accessible when RUM is being inited, may not be accessible at all in bundled apps), extra documentation effort was needed to …

Socket.io client instrumentation

---

.gitlab-ci.yml

Renamed old AWS tokens in gitlab for now. If a release passes with this then will remove. Tested with some Get commands to make sure we have the rights https://cd.splunkdev.com/o11y-gdi/js-maintainers/splunk-otel-js-web-releaser/-/jobs/30260679.

APMI-2209 

---

src/SplunkUserInteractionInstrumentation.ts
test/init.test.ts

Causes error to throw when using react-onclickoutside:
https://github.com/Pomax/react-onclickoutside/blob/15c3cdaed0d8314ac68bc53c7fad7b2c2f3c4ae2/src/index.js#L19

Fix event listeners throwing when useCapture = null

---

src/SplunkExporter.ts
test/SplunkExporter.test.ts

Filter out timings that are before span start caused by missing Timing-Allow-Origin header

Filter out invalid CORS network timings

---

integration-tests/tests/resource-observer/resource-obs.spec.js
integration-tests/tests/resource-observer/resources-postload-disabled.ejs
package-lock.json
package.json
src/index.ts

When postload instrumentation is disabled, any context changes will currently throw with an error

Call postload context hooks only if instrumentation has been loaded

---

.gitlab-ci.yml

for loop generated command `npm publish artifacts/splunk-otel-web-0.14.0-rc.1.tgz`, since it didn't have . infront it thought it was referencing a github repository called artifacts/splunk-otel-web-0.14.0-rc.1.tgz

another release script fix

---

packages/web/src/SplunkWebTracerProvider.ts
packages/web/utils/devServer/index.html

Integrate currently [in-pr fix for performance API time drift](https://github.com/open-telemetry/opentelemetry-js/pull/3434)
There is one adjustment from code in the pr: I also added a layer to flag all HrTimes that should be correct; so we're able to filter out HrTimes that are taken straight from `@opentelemetry/core` package and correct those for drift (xhr, fetch and our errors instrumentations)

Integrate otel's performance clock drift fix

---

packages/session-recorder/src/OTLPLogExporter.ts
packages/session-recorder/src/index.ts

* Remove header no longer needed
* Add `rumAuth` as the primary way to include rum auth token (mirroring main library)

Session replay exporting updates

---

packages/web/integration-tests/tests/context/location-hash.ejs
packages/web/integration-tests/tests/context/xhr-events.ejs
packages/web/src/SplunkContextManager.ts

When a patched `on<event>` property is get before an (instrumented) value is set, it can throw when trying to find original function of null value

Add extra saftey check for value in async context manager

---

packages/web/src/SplunkExporter.ts

Chrome can now have more precise `performance.timeOrigin` than just int timestamp, but due to multiple layers of roundings in otel-js it can lead to cors timestamps (input = 0) to be less than `performance.timeOrigin`

Filter inaccurate CORS timings in case of more precise timeOrigin

---

packages/web/src/SplunkSocketIoClientInstrumentation.ts

The `call` method invokes the callback with `args` array as the first argument instead of spreading them, and as a side effect changes the data flow. The `apply` method instead spreads those args into individual arguments for the function.
[Socket.io documentation](https://socket.io/docs/v3/emitting-events/#acknowledgements) shows that data should be passed as it is received and not wrapped in an array

fix(socketio-instrumentation): use apply instead of call method when invoking the 'on' callback

---

packages/session-recorder/README.md
packages/session-recorder/src/index.ts

This change-set updates the type-definition and quick-start for `SplunkSessionRecorder` to match the preferred default-configuration.

Update `SessionRecorder` type-definitions to match their use

---

package-lock.json
packages/web/package.json
packages/web/src/index.ts
packages/web/test/init.test.ts

Currently ingest will have a different endpoint for otlp data

Use different endpoint when realm + exporter.otlp are used

---

packages/web/src/SplunkFetchInstrumentation.ts

Other than object (`{'X-Test': 'value'}`) and Headers object, there's a third way to pass headers into fetch api of `[name, value][]` (`[['X-Test', 'value']]`) ([spec](https://fetch.spec.whatwg.org/#typedefdef-headersinit)). This currently isn't handled correctly in otel's fetch instrumentation, ending up converting the array into object `{0: 'X-Test,value'}`
Bypassing the bug for now by converting the array into a Headers object
```js
fetch('/some-data', {headers: [['X-Test', 'value']]}).then(response => response.json()).then(console.log);
```

fix fetch instrumentation not handling headers array correctly

---

packages/web/integration-tests/tests/webvitals/webvitals-specific-disabled.ejs
packages/web/integration-tests/tests/webvitals/webvitals.spec.js
packages/web/src/index.ts
packages/web/src/webvitals.ts

Allows users to individually disable specific metrics (if they have their own calculation method) or pass configuration

Make webvitals metrics individually disableable/configurable

---

package-lock.json
packages/web/package.json
packages/web/src/index.ts
packages/web/src/session.ts
packages/web/src/utils.ts
packages/web/test/SessionBasedSampler.test.ts
packages/web/test/session.test.ts

Currently, we only count user interactions as activity when tracking sessions, this PR adds a config option to allow any span to count as activity.

Optionally allow all spans to count as activity

---

packages/web/src/global-utils.ts
packages/web/src/index.ts
packages/web/src/utils.ts
packages/web/test/init.test.ts
packages/web/test/utils.ts

Uses global `window[Symbol.for('opentelemetry.js.api.1')]` to track if more than one instance of `SplunkRum` active within a given context.
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

Protect against multiple instances running in the same context

---

packages/web/integration-tests/tests/errors/index.spec.js
packages/web/integration-tests/tests/errors/views/minified_file_errors.ejs
packages/web/integration-tests/tests/errors/views/script1.min.js
packages/web/integration-tests/tests/errors/views/script2.min.js
packages/web/src/SplunkErrorInstrumentation.ts

retrieve source map ids of files in stacktrace
add source_map_ids to error span attributes

add source_map_ids to error span attributes

---

packages/web/src/SplunkErrorInstrumentation.ts
packages/web/test/index.ts
packages/web/test/stacktrace.test.ts
packages/web/test/utils.ts

This PR adds unit tests for testing the new regex filter for url stack trace parsing in the error instrumentation, which will be used for retrieving source map ids from minified files. 

Update regex filter + unit tests

---

eslint.config.mjs
packages/session-recorder/src/BatchLogProcessor.ts
packages/session-recorder/src/OTLPLogExporter.ts
packages/session-recorder/src/index.ts
packages/session-recorder/src/types.ts
packages/web/performance-tests/injectingProxy/HtmlInjectorTransform.js
packages/web/src/EventTarget.ts
packages/web/src/SessionBasedSampler.ts
packages/web/src/SplunkConnectivityInstrumentation.ts
packages/web/src/SplunkContextManager.ts
packages/web/src/SplunkDocumentLoadInstrumentation.ts
packages/web/src/SplunkErrorInstrumentation.ts
packages/web/src/SplunkLongTaskInstrumentation.ts
packages/web/src/SplunkPageVisibilityInstrumentation.ts
packages/web/src/SplunkPostDocLoadResourceInstrumentation.ts
packages/web/src/SplunkSocketIoClientInstrumentation.ts
packages/web/src/SplunkSpanAttributesProcessor.ts
packages/web/src/SplunkUserInteractionInstrumentation.ts
packages/web/src/SplunkWebSocketInstrumentation.ts
packages/web/src/exporters/common.ts
packages/web/src/exporters/otlp.ts
packages/web/src/exporters/rate-limit.ts
packages/web/src/exporters/zipkin.ts
packages/web/src/index.ts
packages/web/src/session.ts
packages/web/src/upstream/user-interaction/instrumentation.ts
packages/web/test/SplunkExporter.test.ts
packages/web/test/utils.ts

This PR introduces deterministic sorting for classes and interfaces to improve consistency in the structure of our codebase. By sorting members in a predefined order, we can reduce noise in diffs, especially when additional properties or members are added over time. This change ensures that new members will not disrupt the overall order, resulting in smaller diffs.
Just sorting. No need to create tests.

 chore: enable `@typescript-eslint/member-ordering` rule 

---

examples/next-ssr-example/README.md
packages/session-recorder/src/index.ts

Fix bug introduced by the eslint update in #879. Previously, the `++` operator was used, which increments the value after the variable is accessed. We switched to `+=` and moved it before the variable is used, causing issues with the indices.

fix(session-replay): id increment

---

packages/web/src/cookie-session.ts
packages/web/src/index.ts
packages/web/src/local-storage-session.ts
packages/web/src/session.ts
packages/web/src/types.ts
packages/web/src/utils.ts
packages/web/src/utils/storage.ts
packages/web/test/SessionBasedSampler.test.ts
packages/web/test/session.test.ts
packages/web/test/utils.test.ts

Added `init` config option `useLocalStorage` to save session data to local storage instead of cookie. It's mandatory for environments where cookie isn't usable, like Electron apps.
_List Github issue(s) which this PR fixes._

feat: add option to save session data to local storage

---

packages/web/src/index.ts
packages/web/src/types/config.ts

Added persistence flag
Available options:
- `'cookie'` (default): Session state will be stored in a browser cookie.
- `'localStorage'`: Session state will be stored in the browser's localStorage.
If not specified, `'cookie'` will be used as the default storage method.

feat: add `persistence` flag

---

package-lock.json
package.json
packages/integration-tests/src/tests/docload/docload.spec.ts
packages/session-recorder/tsconfig.base.json
packages/web/src/SplunkDocumentLoadInstrumentation.ts
packages/web/tsconfig.base.json

Add 'http.response.status_code' to documentFetch span.
- Fix

fix: Add 'http.response.status_code' to documentFetch span.

---

.gitlab-ci.yml

Set packages for release explicitly to prevent incidental release of private packages

chore: explicitly set packages for release

---

packages/integration-tests/src/tests/docload/docload.spec.ts
packages/web/src/SplunkDocumentLoadInstrumentation.ts

New tag name will be used later
Use `http.status_code` instead of new otel name due to compatibility reasons.
- Integration testing

chore: use old tag name for compatibility - http.status_code

---

packages/web/src/SplunkDocumentLoadInstrumentation.ts

Ignore status 0 - might bring confusion as it can mean status 200 up to 500, due to CORS restriction not possible to find more info.

chore: ignore status 0

---

packages/session-recorder/src/index.ts
packages/web/src/SessionBasedSampler.ts
packages/web/src/SplunkSpanAttributesProcessor.ts
packages/web/src/index.ts
packages/web/src/session/session.ts
packages/web/test/SplunkSpanAttributesProcessor.test.ts
packages/web/test/session.test.ts

This update resolves issues with the `_experimental_allSpansExtendSession` flag, which did not work correctly with the session recorder. Spans created via the session recorder improperly extended sessions in a backgrounded tab.
1. When the session recorder finishes a session in a backgrounded tab, it does not start a new session until the tab returns to the foreground.
2. During this time, the session recorder emits events that are discarded. Before discarding, we call `SplunkRum._internalOnExternalSpanCreated()`, which results in either starting a new session or artificially extending the previous session.
**The changes in this update ensure that the callback is invoked only after confirming that the events will not be discarded.**
The `SplunkRum.getSessionID()` method can return …

fix: do not extend session from discarded session replay spans

---

packages/build-plugins/package-lock.json
packages/build-plugins/src/index.ts
packages/build-plugins/src/utils.ts
packages/build-plugins/src/webpack/index.ts
packages/build-plugins/test/utils.test.ts

Migrate from BannerPlugin to a custom "insert" plugin that runs after source maps are finished.  Use source map content hash as the id instead of the webpack chunk hash
- Manual testing using o11y RUM UI

fix(build-plugins): update inject to use source map hash as the id

---

.size-limit.cjs
packages/integration-tests/src/tests/automation-frameworks/automation-frameworks-disabled.ejs
packages/integration-tests/src/tests/automation-frameworks/automation-frameworks-enabled.ejs
packages/integration-tests/src/tests/automation-frameworks/automation-frameworks.spec.ts
packages/integration-tests/src/tests/bots/bots-disabled.ejs
packages/integration-tests/src/tests/bots/bots-enabled.ejs
packages/integration-tests/src/tests/bots/bots.spec.ts
packages/integration-tests/tsconfig.json
packages/session-recorder/src/index.ts
packages/session-recorder/src/utils.ts
packages/web/src/index.ts
packages/web/src/types/config.ts
packages/web/src/utils/is-bot.ts
packages/web/test/SplunkContextManager.test.ts
packages/web/test/SplunkOtelWeb.test.ts
packages/web/test/api.test.ts
packages/web/test/init.test.ts
packages/web/test/nodejs.test.ts
packages/web/test/utils.ts

Disable bots by default using the https://www.npmjs.com/package/isbot package regex
Add option to disable/enable tracking of bots - disabled by default.
Add option to disable/enable tracking of automation frameworks - enabled by default.

feat: bots & automation frameworks detection

---

package-lock.json
package.json
packages/build-plugins/.mocharc.integration.json
packages/build-plugins/integration-test/integration.test.ts
packages/build-plugins/integration-test/project/package-lock.json
packages/build-plugins/integration-test/project/package.json
packages/build-plugins/integration-test/project/src/common/helpers.js
packages/build-plugins/integration-test/project/src/index.js
packages/build-plugins/integration-test/project/src/other-entry.js
packages/build-plugins/integration-test/project/webpack-utils.js
packages/build-plugins/integration-test/project/webpack.config.devtool.eval.js
packages/build-plugins/integration-test/project/webpack.config.devtool.hidden-source-map.js
packages/build-plugins/integration-test/project/webpack.config.devtool.source-map.js
packages/build-plugins/integration-test/project/webpack.config.no-source-maps.js
packages/build-plugins/integration-test/project/webpack.config.without-plugin.js
packages/build-plugins/package.json
packages/build-plugins/src/utils.ts
packages/build-plugins/tsconfig.json
packages/integration-tests/src/server/server.ts
packages/integration-tests/src/tests/errors/errors.spec.ts
packages/integration-tests/src/tests/errors/views/minified-file-errors.ejs

Created "integration" test within the build-plugins folder for testing behavior with real webpack
Added additional test cases to playwright test to verify that the snippet works properly to get sourceMapId onto the spans

chore(build-plugins): add test coverage for source map id injection

---

.github/actions/install-playwright/action.yml
.github/workflows/check-links.yml
.github/workflows/ci.yml
.github/workflows/tests.yml
packages/web/src/session/cookie-session.ts
tsconfig.eslint.json
vitest.config.mts

The new version of Vitest allows us to run our unit tests in Firefox and WebKit in addition to Chromium. This PR updates the configuration and CI pipeline to enable tests across all three browsers.

chore: run unit tests in WebKit and Firefox

---

.github/actions/install-playwright/action.yml
package-lock.json
packages/build-plugins/README.md
packages/build-plugins/integration-test/integration.test.ts
packages/build-plugins/integration-test/project/package-lock.json
packages/build-plugins/integration-test/project/package.json
packages/build-plugins/integration-test/project/webpack.config.devtool.eval.js
packages/build-plugins/integration-test/project/webpack.config.devtool.hidden-source-map.js
packages/build-plugins/integration-test/project/webpack.config.devtool.source-map.js
packages/build-plugins/integration-test/project/webpack.config.no-source-maps.js
packages/build-plugins/integration-test/project/webpack.config.without-source-maps-options.js
packages/build-plugins/package-lock.json
packages/build-plugins/package.json
packages/build-plugins/src/index.ts
packages/build-plugins/src/webpack/index.ts

* Add input validation check before applying source map upload plugin
* change exported function `o11yWebWebpackPlugin` to exported class `SplunkRumWebpackPlugin`
* change package name to `otel-web-build-plugins`
* move general `applicationName` and `version` options to the top-level of the plugin config
_List Github issue(s) which this PR fixes._
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

chore(build-plugins): update API and add input validation

---

packages/web/src/index.ts

Fix typo that causes different info being logged. Functionality stays the same

fix: typo of disabledByAutomationFrameworkDetection

---

.size-limit.cjs
packages/integration-tests/src/pages/record-page.ts
packages/integration-tests/src/server/render-agent.ts
packages/integration-tests/src/server/server.ts
packages/integration-tests/src/tests/errors/errors.spec.ts
packages/integration-tests/src/tests/extend-activity/all.ejs
packages/integration-tests/src/tests/extend-activity/extend-activity.spec.ts
packages/integration-tests/src/tests/extend-activity/some.ejs
packages/integration-tests/src/tests/long-task/index.ejs
packages/integration-tests/src/tests/long-task/long-task.spec.ts
packages/integration-tests/src/tests/sampling/sampling.ejs
packages/integration-tests/src/tests/sampling/sampling.spec.ts
packages/web/src/global-utils.ts
packages/web/src/index.ts
packages/web/src/session/session.ts

improvement: integration tests

---

packages/session-recorder/src/BatchLogProcessor.ts
packages/session-recorder/src/OTLPLogExporter.ts

Remove deprecated 'unload' event.
Add keepAlive param for data to be sent more reliably.

fix: unload event and data sending

---

packages/web/src/index.ts

Missing SplunkOtelWebConfig and SplunkOtelWebExporterOptions types
Fixes https://github.com/signalfx/splunk-otel-js-web/issues/1076

fix: missing SplunkOtelWebConfig and SplunkOtelWebExporterOptions types

---

packages/web/src/utils/is-bot.ts

Fix issue in IE 11 for legacy build.

fix: is-bot on IE11

---

packages/web/src/exporters/common.ts
packages/web/src/exporters/otlp.ts

The file `packages/web/src/exporters/zipkin.ts` does not contain a sendBeacon check. In IE11, sendBeacon is not defined, so it throws an error.

fix: calling sendBeacon in IE11

---

packages/integration-tests/src/tests/user-interaction/history-ignore.ejs
packages/integration-tests/src/tests/user-interaction/history-ignore.spec.ts
packages/integration-tests/src/tests/user-interaction/history.ejs
packages/web/src/SplunkUserInteractionInstrumentation.ts
packages/web/src/upstream/user-interaction/instrumentation.ts

Ensure that `routeChange` spans are not created for URLs matching the `ignoreUrls` pattern.

feat: respect `ignoreUrls` option for `routeChange` span creation

---

.gitignore
packages/integration-tests/src/tests/errors/errors.spec.ts
packages/web/src/SplunkErrorInstrumentation.ts
packages/web/src/types/type-guards/node.ts

Closes https://github.com/signalfx/splunk-otel-js-web/issues/1276
When the browser fails to load an element — such as an image, video, or script — it triggers an empty event with no message. According to the documentation, this empty error means the resource either failed to load or couldn’t be used. 
New message is introduced saying - `Failed to load <tag_name src="src_attribute_value" />`
https://developer.mozilla.org/en-US/docs/Web/API/Window/error_event
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/error_event

fix: improve error msg for failed resources

---

packages/session-recorder/src/api/api-fetch.ts
packages/session-recorder/src/api/index.ts
packages/session-recorder/src/otlp-log-exporter.ts

- Don't retry rate-limited requests (429 errors)
- Clean up queued logs when rate limits hit

chore(session-recorder): remove 429 from retry logic

---

packages/session-recorder/package.json
packages/session-recorder/src/session-replay/cdn-module-types.d.ts
packages/session-recorder/src/session-replay/cdn-module.ts
packages/session-recorder/tsconfig.base.json
packages/session-recorder/webpack.config.js
pnpm-lock.yaml

This PR adds TypeScript and IntelliSense support for the SplunkSessionRecorder initialization options when the library is used by customers. Previously, it only included partial type definitions — for example, features and other options were resolved to any because the declaration file for this part was missing.

fix(session-recorder): missing types for session recorder init options
